import {Portrait,BananaIcon,CrownIcon} from './ArtUI';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {communityLinks,voteOptions} from './content';
import type {GameSnapshot} from './runtime';
export function CityMap(){return <div className="city-map"><div className="map-crown"><CrownIcon/><span>CROWN TOWER</span><small>CROWN DISTRICT · LOCKED</small></div><div className="map-road"/><div className="map-district"><span>02</span>DOWNTOWN<small>LOCKED</small></div><div className="map-district casino"><span>03</span>CASINO DISTRICT<small>LOCKED</small></div><div className="map-district current"><span>01</span>OUTSKIRTS<small>YOU ARE HERE</small></div><p>NEW MISSIONS. NEW STREETS.</p></div>;}
export function CommunityBoard({view,onVote,onClose}:{view:GameSnapshot;onVote:(s:string)=>Promise<void>;onClose:()=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState('');async function vote(choice:string){setBusy(true);try{await onVote(choice);setError('');}catch{setError('That didn’t stick. Try again.');}finally{setBusy(false);}}return <><div className="season-tag">SEASON 0 <b>ACTIVE</b></div><h3>The story doesn’t move<br/>without the monkes.</h3><p className="board-tagline">MISSIONS · COMMUNITY DECISIONS · NEW DISTRICTS</p><span className="eyebrow">WHICH STREET NEXT?</span><div className="vote-options">{voteOptions.map(choice=><button key={choice} disabled={busy} aria-pressed={view.vote===choice} onClick={()=>void vote(choice)}>{choice}<b>{view.vote===choice?'✓':'→'}</b></button>)}</div><p className="prototype-note">{view.vote?`Your pick: ${view.vote}. `:''}A practice vote, saved on this device. Live community voting is not open yet.</p>{error&&<p role="alert">{error}</p>}<button className="primary small" onClick={onClose}>BACK TO EXPLORING →</button></>;}
export function DiscoveryPanel({view,onNext,onClose,onVote}:{view:GameSnapshot;onNext:(s?:string)=>void;onClose:()=>void;onVote:(s:string)=>Promise<void>}){const e=view.encounter,n=view.node,speaker=n?.speaker;const names={hero:'RICHMONKE',doubter:'THE DOUBTER',owner:'MONKE STOP OWNER',ape:'APEONFONE'};const isReading=e?.kind==='map'||e?.kind==='board';const locked=!!e?.story&&!view.flags.includes(e.flag??'')&&!!(n?.next||n?.choices);return <Dialog open={view.phase==='dialogue'&&!!e} onOpenChange={v=>!v&&onClose()}><DialogContent showCloseButton={!locked} className={`game-menu discovery-panel ${isReading?'panel-'+e?.kind:'panel-npc'} encounter-${e?.id} mood-${n?.mood??'thinking'}`}>
 {!isReading&&<Portrait kind={speaker??'hero'} talking={!!speaker}/>}
 <DialogTitle>{speaker?names[speaker]:e?.title}</DialogTitle><DialogDescription>{e?.id==='ape'?'Concept cameo · collaboration not confirmed.':isReading||e?.kind==='secret'?'TAKE A LOOK · OPTIONAL':e?.story?'MISSION 001 · THE WAY IN':'MONKE CITY'}</DialogDescription>
 {e?.kind==='map'?<><CityMap/><button className="primary small" onClick={onClose}>GOT MY BEARINGS →</button></>:e?.kind==='board'?<CommunityBoard view={view} onVote={onVote} onClose={onClose}/>:<>
 {e?.kind==='tv'&&<div className="tv-static"><CrownIcon/><span>MONKE TV · ON AIR</span><i/></div>}
 <p className="dialogue-line" key={`${e?.id}-${view.nodeId}`}>{n?.text}</p>
 {n?.choices?<div className="dialogue-choices">{n.choices.map(choice=><button key={choice.label} className="primary small" onClick={()=>onNext(choice.label)}>{choice.label}<span>→</span></button>)}</div>:<button className="primary small dialogue-next" onClick={()=>onNext()}>{n?.next?'NEXT':e?.id==='rich'?'CONTINUE JOURNEY':'ON WE GO'} <span>→</span></button>}
 </>}
 </DialogContent></Dialog>;}
export function Ending({view,onReplay}:{view:GameSnapshot;onReplay:()=>void}){const[skip,setSkip]=useState(false),[notice,setNotice]=useState('');const t=skip||view.reduced?20:view.phaseTime,final=t>=10;return <section className="ending episode-ending" aria-label="Mission one ending">
 {t<2?<div className="ending-beat"><span className="eyebrow">DOWNTOWN ACCESS</span><h2>MONKE CITY</h2></div>:t<4?<div className="ending-beat" key="complete"><span className="eyebrow">MISSION #001</span><h2>COMPLETE!</h2></div>:t<7?<div className="ending-beat" key="seven"><h2>MONKE STARTED<br/>WITH <em>$7.</em></h2></div>:t<10?<div className="ending-beat" key="rest"><h2>THE REST<br/><em>HAS NOT BEEN<br/>WRITTEN YET.</em></h2></div>:<div className="episode-finale"><span className="eyebrow">MISSION #001 · COMPLETE</span><h2>THE REST<br/><em>IS UP TO THE MONKES.</em></h2><div className="next-mission">MISSION #002 <b>LOCKED</b><span>THE NEXT CHAPTER IS ON ITS WAY.</span></div><p>THE COMMUNITY WRITES WHAT HAPPENS NEXT.</p><div className="final-buttons">{(['community','story'] as const).map(key=>communityLinks[key]?<a key={key} className="primary small" href={communityLinks[key]!} target="_blank" rel="noopener noreferrer">{key==='community'?'JOIN THE COMMUNITY':'FOLLOW THE STORY'} ↗</a>:<button key={key} className="primary small" onClick={()=>setNotice('The official links aren’t open yet. Your place in the story is saved.')}>{key==='community'?'JOIN THE COMMUNITY':'FOLLOW THE STORY'} ↗</button>)}</div>{notice&&<small className="link-notice" role="status">{notice}</small>}<div className="episode-receipt"><BananaIcon/> {view.bananas}/5 finds <span>· CITY TICKET EARNED</span></div><button className="text-button" onClick={onReplay}>PLAY THE EPISODE AGAIN</button></div>}
 {!final&&<button className="text-button skip-ending" onClick={()=>setSkip(true)}>SKIP TO NEXT CHAPTER →</button>}
 </section>;}
export function GameMenu({open,view,onClose,onRestart}:{open:boolean;view:GameSnapshot;onClose:()=>void;onRestart:()=>void}){const[confirm,setConfirm]=useState(false);return <Dialog open={open} onOpenChange={v=>{if(!v){setConfirm(false);onClose();}}}><DialogContent className="game-menu"><DialogTitle>TAKE A BREATHER.</DialogTitle><DialogDescription>Your journey is saved on this device.</DialogDescription><div className="pause-objective"><span className="eyebrow">UP NEXT</span><h3>{view.objective?.label??'The next chapter.'}</h3><p><BananaIcon/> {view.bananas}/5 finds · {view.secrets}/3 secrets{view.ticket?' · City ticket ready':''}</p></div><div className="pause-controls"><span>A / D <b>MOVE</b></span><span>SPACE <b>JUMP</b></span><span>E <b>INTERACT</b></span></div><p className="prototype-note">Cash and banana coins are game items, not $RICH prices or real money.</p><button className="primary small" onClick={onClose}>BACK TO IT →</button>{confirm?<div className="restart-confirm"><p>Start from $7 and clear this episode’s progress?</p><button onClick={()=>{setConfirm(false);onRestart();}}>Start from the motel</button><button onClick={()=>setConfirm(false)}>Keep my journey</button></div>:<button className="text-button" onClick={()=>setConfirm(true)}>Start the episode again</button>}</DialogContent></Dialog>;}
