'use client';
import { useEffect, useRef, useState } from 'react';
import { AudioManager, Camera, GameState, InteractionPoint, MissionSystem, Player, SceneTransition, Phase } from './systems';
import { GameScene } from './environment';
import { registerGameTools } from './webmcp';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

function GameHUD({phase,near,onInteract}:{phase:Phase;near:boolean;onInteract:()=>void}) { return <><header className="hud"><div className="wallet"><span>NET WORTH</span><strong>$7<span className="wallet-dot">●</span></strong></div><div className="mission"><span>MISSION #001</span><b>GET INTO MONKE CITY</b></div></header>{phase==='playing'&&near&&<button className="interact" onClick={onInteract}><kbd>E</kbd><span>READ SIGN</span> ↗</button>}</>; }
function DialogueSystem({open,elapsed,onContinue}:{open:boolean;elapsed:number;onContinue:()=>void}){if(!open)return null;return <div className="dialogue" role="dialog" aria-label="Road sign"><span className="eyebrow">OUTSKIRTS / ROADSIDE</span><h2>MONKE CITY <em>3 KM →</em></h2><p>“Everybody wants in.”</p><p className={elapsed>1.3?'line-visible':'line-hidden'}>“Few make it.”</p><button className="primary small" disabled={elapsed<1.6} onClick={onContinue}>CONTINUE <span>→</span></button></div>;}
function GameMenu({open,onClose,onReplay}:{open:boolean;onClose:()=>void;onReplay:()=>void}) { const [tab,setTab]=useState('STORY');const copy:Record<string,string>={STORY:'Seven dollars. One big city. Your story starts outside Monke Motel.',MISSIONS:'MISSION #001 — Get into Monke City. Follow the road, read the sign, and reach the overlook.',$RICH:'Official project details will be added here. No token information has been supplied yet.',COMMUNITY:'The city is better with company. Official community links are coming soon.'};return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="game-menu"><DialogTitle>PAUSED IN MONKE CITY</DialogTitle><DialogDescription>Take a breath. The city can wait.</DialogDescription><nav>{Object.keys(copy).map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><p>{copy[tab]}</p><button className="primary small" onClick={onClose}>BACK TO THE STREETS →</button><button className="text-button" onClick={onReplay}>Restart journey</button></DialogContent></Dialog>; }
export default function Game(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<{state:GameState;player:Player;camera:Camera;audio:AudioManager;transition:SceneTransition}|null>(null),keys=useRef(new Set<string>());
 const [phase,setPhase]=useState<Phase>('loading'),[intro,setIntro]=useState(0),[muted,setMuted]=useState(true),[menu,setMenu]=useState(false),[near,setNear]=useState(false),[elapsed,setElapsed]=useState(0),[progress,setProgress]=useState(0);
 const change=(p:Phase)=>{if(engine.current){engine.current.state.phase=p;engine.current.transition.reset();}setPhase(p);};
 const interact=()=>{const e=engine.current;if(e&&e.state.phase==='playing'&&new InteractionPoint().nearby(e.player.x)){e.player.velocity=0;e.audio.tone(440,.2,.035);change('dialogue');}};
 const continueGame=()=>{if(engine.current){engine.current.state.signRead=true;change('playing');}};
 const replay=()=>{const e=engine.current;if(!e)return;e.player.x=370;e.player.velocity=0;e.camera.x=0;e.camera.descent=1;e.state.signRead=false;e.state.paused=false;setMenu(false);change('ready');};
 useEffect(()=>{
  const c=canvas.current!,ctx=c.getContext('2d')!,state=new GameState(),player=new Player(),camera=new Camera(),audio=new AudioManager(),transition=new SceneTransition(),scene=new GameScene(),mission=new MissionSystem(),point=new InteractionPoint();engine.current={state,player,camera,audio,transition};scene.load();let raf=0,last=0,time=0,tick=0,lastFoot=0,logicalW=1280,visible=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const resize=()=>{const dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(innerWidth*dpr);c.height=Math.round(innerHeight*dpr);logicalW=800*innerWidth/innerHeight;};resize();addEventListener('resize',resize);
  const down=(e:KeyboardEvent)=>{if(['ArrowLeft','ArrowRight','a','d','A','D','e','E'].includes(e.key)){if(e.target instanceof HTMLButtonElement&&e.key==='Enter')return;e.preventDefault();keys.current.add(e.key.toLowerCase());}if(e.key.toLowerCase()==='e'&&state.phase==='playing'&&!state.paused&&point.nearby(player.x)){player.velocity=0;state.phase='dialogue';transition.reset();setPhase('dialogue');audio.tone(440,.2,.035);}if(e.key==='Escape'){setMenu(v=>!v);keys.current.clear();}};
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();};const visibility=()=>{visible=!document.hidden;last=0;blur();};addEventListener('keydown',down);addEventListener('keyup',up);addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
  const frame=(now:number)=>{const dt=Math.min(.04,(now-last)/1000||0);last=now;if(visible&&!state.paused){time+=dt;transition.update(dt);const t=transition.elapsed;if(state.phase==='loading'&&t>.8){state.phase='intro';transition.reset();setPhase('intro');}else if(state.phase==='intro'){setIntro(Math.min(2,Math.floor(t/1.5)));if(t>4.5){state.phase='ready';setPhase('ready');}}else if(state.phase==='arriving'){camera.descent=reduced?0:Math.pow(1-Math.min(1,t/2.2),3);if(t>2.2){camera.descent=0;state.phase='playing';transition.reset();setPhase('playing');}}else if(state.phase==='playing'){const d=(keys.current.has('d')||keys.current.has('arrowright')?1:0)-(keys.current.has('a')||keys.current.has('arrowleft')?1:0);player.update(dt,d);if(!state.signRead&&player.x>3890)player.x=3890;camera.update(dt,player,logicalW,reduced);if(Math.abs(player.velocity)>20&&time-lastFoot>.32){audio.footstep();lastFoot=time;}if(mission.shouldEnd(player.x,state.signRead)){state.phase='ending';transition.reset();setPhase('ending');audio.tone(523,.6,.04);}}else if(state.phase==='dialogue'){const target=Math.max(0,player.x-logicalW*.36);camera.x+=(target-camera.x)*dt*1.6;}else if(state.phase==='ending'){camera.x+=(Math.max(0,4800-logicalW)-camera.x)*dt*.7;}
  if(time-tick>.1){tick=time;setNear(point.nearby(player.x));setElapsed(transition.elapsed);setProgress(Math.min(100,(player.x-370)/4060*100));}}
  ctx.setTransform(c.width/logicalW,0,0,c.height/800,0,0);scene.draw(ctx,logicalW,800,camera,player,time,reduced,state.phase);raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);
  return()=>{cancelAnimationFrame(raf);audio.dispose();removeEventListener('resize',resize);removeEventListener('keydown',down);removeEventListener('keyup',up);removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);engine.current=null;};
 },[]);
 useEffect(()=>{if(engine.current)engine.current.state.paused=menu;keys.current.clear();},[menu]);
 useEffect(()=>registerGameTools(()=>{const e=engine.current;return e?{phase:e.state.phase,mission:'001',x:Math.round(e.player.x),netWorth:e.state.netWorth,signRead:e.state.signRead}:{phase:'loading'};},()=>{if(engine.current?.state.phase!=='ready')throw new Error('Wait for the title screen before starting');change('arriving');return{phase:'arriving'};}),[]);
 const touch=(direction:string)=>(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(direction);};const release=()=>keys.current.clear();
 const active=['arriving','playing','dialogue','ending'].includes(phase);
 return <main className={`game phase-${phase}`}><canvas ref={canvas} aria-label="Monke City cartoon world. Walk right from the motel, read the roadside sign, then reach the city overlook."/><div className="film-grain"/><div className="brand">RICHMONKE<span> $RICH</span></div><div className="top-actions"><button onClick={()=>{if(engine.current)setMuted(engine.current.audio.toggle());}} aria-label={muted?'Turn sound on':'Mute sound'}>{muted?'◌':'◉'} <span>SOUND {muted?'OFF':'ON'}</span></button><button className="menu-button" aria-label="Open game menu" onClick={()=>setMenu(true)}>☰</button></div>
 {phase==='loading'&&<div className="loading"><div className="load-bars">▰ ▰ ▰</div><span>LOADING MONKE CITY...</span></div>}
 {phase==='intro'&&<div className="intro" key={intro}><span>{['NET WORTH','LOCATION','MISSION'][intro]}</span><strong>{['$7','MONKE MOTEL','GET RICH.'][intro]}</strong></div>}
 {phase==='ready'&&<section className="start-screen"><div className="chapter-pill"><i/> A RICHMONKE STORY · CHAPTER 01</div><h1>MONKE<br/><em>CITY</em><span className="title-star">✦</span></h1><p>START WITH <b>$7.</b> <span>DREAM BIGGER.</span></p><button className="primary" onClick={()=>{engine.current?.audio.tone(330,.2,.04);change('arriving');}}>START JOURNEY <span>→</span></button><div className="start-note">ONE MONKE. A WHOLE CITY. YOUR MOVE.</div></section>}
 {active&&<GameHUD phase={phase} near={near} onInteract={interact}/>}
 <DialogueSystem open={phase==='dialogue'} elapsed={elapsed} onContinue={continueGame}/>
 {phase==='ending'&&<div className="ending"><span className="eyebrow">MISSION #001</span><h2>GET INTO<br/>MONKE CITY.</h2><p className={elapsed>1.5?'line-visible':'line-hidden'}>TO BE CONTINUED.</p>{elapsed>2.5&&<button className="primary small" onClick={replay}>PLAY AGAIN ↺</button>}</div>}
 <footer><div className="district"><i/><span>{progress>75?'DOWNTOWN OVERLOOK':'MONKE MOTEL / OUTSKIRTS'}</span></div>{phase==='playing'?<div className="controls-hint"><kbd>A</kbd><kbd>D</kbd><span>MOVE</span><b>→</b><span>FOLLOW THE LIGHTS</span></div>:<span className="build-label">THE JOURNEY STARTS AT THE BOTTOM.</span>}<span className="chapter-number">01 <span>/ THE OUTSKIRTS</span></span></footer>
 {phase==='playing'&&<><div className="touch-controls"><button aria-label="Walk left" onPointerDown={touch('a')} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}>←</button><button aria-label="Walk right" onPointerDown={touch('d')} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}>→</button></div><div className="journey-progress"><span style={{width:`${progress}%`}}/></div></>}
 <GameMenu open={menu} onClose={()=>setMenu(false)} onReplay={replay}/></main>;
}
