import { useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { communityLinks, mission001, voteOptions } from './content';
import type { GameSnapshot } from './runtime';
export function CityMap(){return <div className="city-map"><div className="map-crown">♛<span>CROWN DISTRICT</span><small>LOCKED</small></div><div className="map-road"/><div className="map-district"><span>02</span>DOWNTOWN<small>LOCKED</small></div><div className="map-district casino"><span>03</span>CASINO DISTRICT<small>LOCKED</small></div><div className="map-district current"><span>01</span>OUTSKIRTS<small>● YOU ARE HERE</small></div><p>THE WORLD GROWS WITH EVERY MISSION.</p></div>;}
export function CommunityBoard({view,onVote,onClose}:{view:GameSnapshot;onVote:(choice:string)=>Promise<void>;onClose:()=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState('');async function vote(choice:string){setBusy(true);setError('');try{await onVote(choice);}catch{setError('Could not save. Try again.');}finally{setBusy(false);}}
 return <><div className="board-missions"><div><b>001</b><span>GET INTO MONKE CITY<small>ACTIVE</small></span></div><div><b>002</b><span>NEXT CHAPTER<small>LOCKED</small></span></div><div><b>003</b><span>MORE OF THE CITY<small>LOCKED</small></span></div><div><b>???</b><span>CROWN DISTRICT<small>LOCKED</small></span></div></div><span className="eyebrow">COMMUNITY DECISION</span><h3>Where should the story go next?</h3><div className="vote-options">{voteOptions.map(option=><button key={option} disabled={busy} aria-pressed={view.vote===option} onClick={()=>void vote(option)}><span>{view.vote===option?'●':'○'}</span>{option}<b>↗</b></button>)}</div><p className="prototype-note">{view.vote?`Your prototype choice: ${view.vote}. `:'Choose a district. '}Saved only on this device — not a live community vote.</p>{error&&<p role="alert">{error}</p>}<p className="board-tagline">THE COMMUNITY SHAPES MONKE CITY.</p><button className="primary small" onClick={onClose}>BACK TO THE STREETS →</button></>;
}
export function DiscoveryPanel({view,onNext,onClose,onVote}:{view:GameSnapshot;onNext:(choice?:string)=>void;onClose:()=>void;onVote:(choice:string)=>Promise<void>}){
 const e=view.encounter;return <Dialog open={view.phase==='dialogue'&&!!e} onOpenChange={v=>!v&&onClose()}><DialogContent className={`game-menu discovery-panel panel-${e?.kind??'none'}`}><DialogTitle>{e?.title}</DialogTitle><DialogDescription>{e?.kind==='secret'?'A little off the beaten path.':e?.id==='ape'?'Concept encounter · placeholder appearance · collaboration not confirmed.':e?.kind==='tv'?'A story from the streets of Monke City.':'MISSION #001 / THE OUTSKIRTS'}</DialogDescription>
 {e?.kind==='map'?<><CityMap/><button className="primary small" onClick={onClose}>MAP DISCOVERED →</button></>:e?.kind==='board'?<CommunityBoard view={view} onVote={onVote} onClose={onClose}/>:<>
 {e?.kind==='tv'&&<div className="tv-static"><span>● LIVE FROM MONKE CITY</span><i/></div>}
 {e?.id==='ape'&&view.node?.effect==='phone'&&<div className="phone-transmission"><span>THE STORY &gt; THE CHART</span><div>╱╲╱╲__╱╲</div><small>No prices. No promises. Just a journey.</small></div>}
 <p className="dialogue-line" key={`${e?.id}-${view.nodeId}`}>{view.node?.text}</p>
 {view.node?.choices?<div className="dialogue-choices">{view.node.choices.map(choice=><button key={choice.label} className="primary small" onClick={()=>onNext(choice.label)}>{choice.label} <span>→</span></button>)}</div>:<button className="primary small" onClick={()=>onNext()}>{view.node?.next?'CONTINUE':'LET’S GO'} →</button>}
 </>}
 </DialogContent></Dialog>;
}
export function Ending({view,onReplay}:{view:GameSnapshot;onReplay:()=>void}){const[linkNotice,setLinkNotice]=useState('');return <section className="ending upgraded-ending"><span className="eyebrow">MISSION #{mission001.id} COMPLETE</span><h2>YOUR FIRST STEP.<br/><em>A WHOLE CITY AHEAD.</em></h2><div className="end-stats"><div><span>NET WORTH</span><strong>${view.netWorth}</strong><small>FICTIONAL GAME CASH</small></div><div><span>MONKE CITY ACCESS</span><strong>8%</strong><small>STORY PROGRESS</small></div><div><span>MONKE FINDS</span><strong>🍌 {view.bananas}/5</strong><small>{view.bananas===5?'EARLY MONKE UNLOCKED':'MORE SECRETS TO FIND'}</small></div></div><p className="final-motto">NOBODY REACHES THE TOP<br/>IN ONE MISSION.</p><div className="next-mission">MISSION #002 <b>LOCKED</b><span>COMING SOON</span></div><h3>THE JOURNEY CONTINUES.</h3><span className="eyebrow">CONTINUE THE JOURNEY</span><div className="final-buttons">{(['community','story'] as const).map(key=>communityLinks[key]?<a className="primary small" key={key} href={communityLinks[key]!} target="_blank" rel="noopener noreferrer">{key==='community'?'JOIN THE COMMUNITY':'FOLLOW THE STORY'} ↗</a>:<button className="primary small" key={key} onClick={()=>setLinkNotice('Official links are coming soon. Your mission progress is saved on this device.')}>{key==='community'?'JOIN THE COMMUNITY':'FOLLOW THE STORY'} ↗</button>)}</div>{linkNotice&&<small role="status" className="link-notice">{linkNotice}</small>}<button className="text-button" onClick={onReplay}>↺ Explore again from the motel</button></section>;}
export function GameMenu({open,view,onClose,onRestart}:{open:boolean;view:GameSnapshot;onClose:()=>void;onRestart:()=>void}){const[confirm,setConfirm]=useState(false);return <Dialog open={open} onOpenChange={v=>{if(!v){setConfirm(false);onClose();}}}><DialogContent className="game-menu"><DialogTitle>PAUSED IN MONKE CITY</DialogTitle><DialogDescription>Your progress saves on this device.</DialogDescription><div className="pause-objective"><span className="eyebrow">NEXT OBJECTIVE</span><h3>{view.objective?.label??'Mission complete. More chapters coming soon.'}</h3><p>🍌 {view.bananas}/5 · Secrets {view.secrets}/3</p></div><div className="pause-controls"><span>A / D <b>MOVE</b></span><span>SPACE <b>JUMP</b></span><span>E <b>INTERACT</b></span></div><p className="prototype-note">All cash and collectibles are fictional game progress with no real-world monetary value. Community choices are device-local prototypes.</p><button className="primary small" onClick={onClose}>BACK TO THE JOURNEY →</button>{confirm?<div className="restart-confirm"><p>Restart this mission and clear its local progress?</p><button onClick={()=>{setConfirm(false);onRestart();}}>Yes, start fresh</button><button onClick={()=>setConfirm(false)}>Keep progress</button></div>:<button className="text-button" onClick={()=>setConfirm(true)}>Start a fresh journey</button>}</DialogContent></Dialog>;}
