import {Children,cloneElement,isValidElement,type ReactNode} from 'react';
export type Language='en'|'es';
let language:Language='en';
export function setLanguage(value:Language){language=value;try{localStorage.setItem('richmonke.language',value);}catch{}if(typeof document!=='undefined')document.documentElement.lang=value;}
export function readLanguage():Language{try{return localStorage.getItem('richmonke.language')==='es'?'es':'en';}catch{return 'en';}}
export const spanish:Record<string,string>={
 'TAP TO INTERACT':'TOCA PARA INTERACTUAR','Monke City. Use the on-screen arrows to move and jump. Tap interaction buttons.':'Monke City. Usa las flechas de la pantalla para moverte y saltar. Toca los botones para interactuar.',
 'USE THE ARROWS TO MOVE':'USA LAS FLECHAS PARA MOVERTE','TAP ↑ TO JUMP':'TOCA ↑ PARA SALTAR','TAP AN OBJECT TO INTERACT':'TOCA EL BOTÓN PARA INTERACTUAR','Close':'Cerrar','CROWN DISTRICT':'DISTRITO CROWN','DOWNTOWN':'CENTRO','OUTSKIRTS':'AFUERAS','YOU ARE HERE':'ESTÁS AQUÍ','MISSION':'MISIÓN','LOCKED':'BLOQUEADA','NEXT DISTRICT':'PRÓXIMO DISTRITO','THE COMMUNITY':'LA COMUNIDAD','SHAPES WHAT’S NEXT.':'DECIDE EL FUTURO.','SUPPLY':'SUMINISTROS','+1 FIND!':'+1 HALLAZGO!',
 'FROM ZERO TO':'DE CERO A','RICH MONKE':'RICH MONKE','One city. One monke. One mission.':'Una ciudad. Un monke. Una misión.','PLAY THE GAME':'JUGAR','CONTINUE JOURNEY':'CONTINUAR','Start a fresh journey':'Empezar de nuevo','A RICHMONKE STORY · AIM FOR THE CROWN.':'UNA HISTORIA RICHMONKE · VE A POR LA CORONA.',
 'COMMUNITY':'COMUNIDAD','SOUND':'SONIDO','OFF':'NO','ON':'SÍ','Turn sound on':'Activar sonido','Mute sound':'Silenciar','Open game menu':'Abrir menú','Open RICHMONKE on X':'Abrir RICHMONKE en X','Open RICHMONKE Telegram':'Abrir Telegram de RICHMONKE','LOADING MONKE CITY...':'CARGANDO MONKE CITY...',
 'NET WORTH':'PATRIMONIO','MISSION #001':'MISIÓN #001','Get into Monke City':'Entra en Monke City','Meet the local':'Conoce al vecino','Discover Monke Stop':'Descubre Monke Stop','Head for the crown':'Ve a por la corona','Reach the overlook':'Llega al mirador','Look around · city exit →':'Explora · salida a la ciudad →','Episode complete':'Episodio completado','NEW OBJECTIVE!':'¡NUEVO OBJETIVO!','JUST A STUMBLE. KEEP GOING.':'SOLO UN TROPIEZO. SIGUE ADELANTE.',
 'A / D — MOVE':'A / D — MOVERSE','SPACE — JUMP':'ESPACIO — SALTAR','E — TAKE A LOOK':'E — EXAMINAR','MOVE':'MOVERSE','JUMP':'SALTAR','INTERACT':'INTERACTUAR','SPACE':'ESPACIO','Walk left':'Caminar a la izquierda','Walk right':'Caminar a la derecha','Jump':'Saltar','EARLY MONKE!':'¡MONKE PIONERO!','BOTH FOUND. NICE.':'LOS DOS ENCONTRADOS. ¡BIEN!',
 'TALK':'HABLAR','ENTER MONKE STOP':'ENTRAR EN MONKE STOP','TO THE CITY →':'A LA CIUDAD →','VIEW MAP':'VER MAPA','WATCH':'VER','CHECK BOARD':'VER TABLÓN','CHECK $RICH':'VER $RICH','CITY MAP':'MAPA DE LA CIUDAD','MONKE CITY BOARD':'TABLÓN DE MONKE CITY','EXIT':'SALIDA','THE DOUBTER':'EL ESCÉPTICO','MONKE STOP OWNER':'DUEÑO DE MONKE STOP','SHOPKEEPER':'TENDERO','THE SHOPKEEPER':'EL TENDERO',
 'Monke City? You started with seven bucks.':'¿Monke City? Empezaste con siete dólares.','SEVEN IS A START.':'SIETE ES UN COMIENZO.','GOT A BETTER IDEA?':'¿TIENES UNA IDEA MEJOR?','Seven is enough to start.':'Siete bastan para empezar.','Staying broke? Terrible idea.':'¿Seguir sin un duro? Mala idea.','Then start walking. Monke Stop is ahead.':'Pues camina. Monke Stop está ahí delante.',
 'Monke City gets bigger with every mission.':'Monke City crece con cada misión.','$7. One monke. One city. One journey.':'7 $. Un monke. Una ciudad. Un viaje.','Missions. Decisions. New districts.':'Misiones. Decisiones. Nuevos distritos.','First time in Monke City?':'¿Primera vez en Monke City?','Not for long.':'Por poco tiempo.','Heh. I like this one.':'Je. Este me cae bien.','The token of the RichMonke universe.':'El token del universo RichMonke.','Story. City. Community.':'Historia. Ciudad. Comunidad.',
 'MISSION 001 · THE WAY IN':'MISIÓN 001 · LA ENTRADA','TAKE A LOOK · OPTIONAL':'EXAMINAR · OPCIONAL','NEXT':'SIGUIENTE','NEXT →':'SIGUIENTE →','BACK →':'VOLVER →','ON WE GO':'SEGUIMOS','Next line':'Siguiente frase','Back to the shop':'Volver a la tienda','Close inspection':'Cerrar inspección','Optional · choose a district':'Opcional · elige un distrito','Practice vote · saved on this device.':'Voto de prueba · guardado en este dispositivo.','Casino District':'Distrito del casino','Downtown':'Centro','Harbor':'Puerto','Try again.':'Inténtalo de nuevo.',
 'TAKE A BREATHER.':'TÓMATE UN RESPIRO.','Your journey is saved on this device.':'Tu progreso se guarda en este dispositivo.','UP NEXT':'SIGUIENTE OBJETIVO','The next chapter.':'El próximo capítulo.','finds':'hallazgos','Cash and banana coins are game items, not $RICH prices or real money.':'El dinero y las monedas banana son objetos del juego, no precios de $RICH ni dinero real.','BACK TO IT →':'VOLVER AL JUEGO →','Start from $7 and clear this episode’s progress?':'¿Empezar con 7 $ y borrar el progreso de este episodio?','Start from the motel':'Empezar desde el motel','Keep my journey':'Conservar mi progreso','Start the episode again':'Reiniciar el episodio',
 'THE OUTSKIRTS':'LAS AFUERAS','MONKE MOTEL / OUTSKIRTS':'MONKE MOTEL / AFUERAS','MONKE STOP / OPEN ALL NIGHT':'MONKE STOP / ABIERTO TODA LA NOCHE','CROWN TOWER OVERLOOK':'MIRADOR DE CROWN TOWER','EVERY MONKE STARTS SOMEWHERE.':'TODO MONKE EMPIEZA EN ALGÚN LUGAR.','/ THE OUTSKIRTS':'/ LAS AFUERAS','YOUR JOURNEY CONTINUES':'TU VIAJE CONTINÚA','THE OUTSKIRTS · START: $7':'LAS AFUERAS · INICIO: 7 $','WARM LIGHTS. BIG PLANS.':'LUCES CÁLIDAS. GRANDES PLANES.','THE WAY UP':'EL CAMINO A LA CIMA','THE WAY UP →':'HACIA LA CIMA →','NEXT: CROWN TOWER':'SIGUIENTE: CROWN TOWER','DOWNTOWN ACCESS':'ACCESO AL CENTRO',
 'Answer the phone':'Contesta al teléfono','PRESS E TO ANSWER':'PULSA E PARA CONTESTAR','TAP TO ANSWER':'TOCA PARA CONTESTAR','Your ride is here.':'Tu coche ha llegado.',"It's time to get rich.":'Es hora de hacerse rico.','INCOMING CALL':'LLAMADA ENTRANTE','UNKNOWN CALLER':'NÚMERO DESCONOCIDO','THE CITY IS YOURS.':'LA CIUDAD ES TUYA.','THE MISSION HAS JUST BEGUN.':'LA MISIÓN ACABA DE EMPEZAR.','REPLAY':'VOLVER A JUGAR','MISSION #001 · COMPLETE':'MISIÓN #001 · COMPLETADA','ONE MONKE.':'UN MONKE.','ONE CITY.':'UNA CIUDAD.','ONE JOURNEY.':'UN VIAJE.',
 'Sound is unavailable in this browser.':'El sonido no está disponible en este navegador.','Monke City. Move with A and D, jump with Space, interact with E.':'Monke City. Muévete con A y D, salta con Espacio e interactúa con E.',
};
export function t(value:string):string{if(language==='en')return value;const trimmed=value.trim();const coins=trimmed.match(/^(\d+) of (\d+) banana coins$/);if(coins)return `${coins[1]} de ${coins[2]} monedas banana`;if(spanish[trimmed])return value.replace(trimmed,spanish[trimmed]);if(trimmed.startsWith('NEW OBJECTIVE! '))return '¡NUEVO OBJETIVO! '+t(trimmed.slice(15));return value;}
/** Translate presentation strings only: dialogue choice IDs and game state remain stable. */
export function localize(node:ReactNode):ReactNode{return Children.map(node,child=>{if(typeof child==='string')return t(child);if(!isValidElement(child))return child;const props=child.props as Record<string,unknown>;const changes:Record<string,unknown>={};for(const key of ['aria-label','title'])if(typeof props[key]==='string')changes[key]=t(props[key]);if(props.children!==undefined)changes.children=localize(props.children as ReactNode);return cloneElement(child,changes);});}
