import assert from 'node:assert/strict';
import { Player, GameState, Camera } from './systems';
import { PlayerController, CollectibleSystem, ProgressStore, AchievementSystem, LocalVoteAdapter } from './gameplay';
import { GameRuntime } from './runtime';
import { encounters, platforms, pickups, mission001 } from './content';
const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v),removeItem:(k:string)=>memory.delete(k)},configurable:true});
const dt=1/120;
function step(g:GameRuntime,seconds:number,direction=0){for(let i=0;i<seconds/dt;i++)g.update(dt,direction);}
function open(g:GameRuntime,id:string){const e=encounters.find(e=>e.id===id)!;g.state.scene=e.scene;g.player.x=e.x;g.player.y=662;g.player.vy=0;g.player.grounded=true;g.setPhase('playing');g.interact();assert.equal(g.dialogue.encounter?.id,id);}
function finish(g:GameRuntime){let count=0;while(g.state.phase==='dialogue'&&count++<20){g.advance(g.dialogue.node?.choices?.[0].label);}assert.equal(g.state.phase,'playing');}
let p=new Player(),controller=new PlayerController();for(let i=0;i<120;i++)controller.update(p,'street',dt,1);assert(p.velocity>150);const x=p.x;for(let i=0;i<120;i++)controller.update(p,'street',dt,0);assert(p.velocity<.01);assert(p.x-x<13);
p=new Player();p.x=620;for(let i=0;i<120;i++)controller.update(p,'street',dt,1);assert(p.x<=652);controller.jump.request(p);let lowest=662;for(let i=0;i<190;i++){controller.update(p,'street',dt,1);lowest=Math.min(lowest,p.y);}assert(lowest<540);assert(p.x>753);assert(p.grounded);assert.equal(p.y,662);
// Every raised collectible has a physically reachable jump from its support.
for(const id of ['banana-1','banana-2','banana-3','banana-5']){const item=pickups.find(i=>i.id===id)!;const state=new GameState();state.scene=item.scene;const q=new Player();q.x=item.x;const support=platforms.filter(s=>s.scene===item.scene&&q.x>s.x&&q.x<s.x+s.width).sort((a,b)=>a.y-b.y)[0];q.y=support?.y??662;q.grounded=true;controller.jump.request(q);const sys=new CollectibleSystem();for(let i=0;i<120;i++){controller.update(q,state.scene,dt,0);sys.collect(state,q);}assert(state.collected.has(id),id+' must be reachable');}

// Walk the complete episode through the real controller, without position jumps.
const transcript:string[]=[];
function completeDialogue(g:GameRuntime){let n=0;while(g.state.phase==='dialogue'&&n++<8){transcript.push(g.dialogue.node?.text??'');g.advance(g.dialogue.node?.choices?.[0].label);}assert.equal(g.state.phase,'playing');}
function settle(g:GameRuntime){for(let i=0;i<400&&g.state.phase!=='playing';i++){if(g.state.phase==='dialogue')completeDialogue(g);else g.update(dt,0);}}
function walk(g:GameRuntime,target:number){const scene=g.state.scene;let seconds=0;while(Math.abs(g.player.x-target)>5&&g.state.phase!=='ending'&&seconds<65){if(g.state.phase==='dialogue')completeDialogue(g);if(g.state.phase==='travel'){settle(g);if(g.state.scene!==scene)return;}if(g.state.scene!==scene)return;const dir=Math.sign(target-g.player.x);const obstacle=platforms.some(s=>s.scene===scene&&s.kind!=='ledge'&&((dir>0&&s.x-g.player.x>23&&s.x-g.player.x<92)||(dir<0&&g.player.x-s.x-s.width>23&&g.player.x-s.x-s.width<92)));if(obstacle&&g.player.grounded)g.jump();g.update(dt,dir);seconds+=dt;}assert(seconds<65,'route must not stall');}
const g=new GameRuntime();g.start();settle(g);assert.equal(g.state.netWorth,7);walk(g,825);assert.equal(g.state.netWorth,8,'first reward follows first jump');step(g,.7);assert(g.state.flags.has('jumped'));walk(g,1210);assert.equal(g.state.netWorth,10);assert(g.state.flags.has('doubter'));walk(g,1420);settle(g);assert.equal(g.state.scene,'stop');assert(g.state.flags.has('stop'));assert.equal(g.objective()?.id,'leave');
// All three shop displays can be skipped without losing the main story.
walk(g,110);g.interact();settle(g);assert.equal(g.state.scene,'street');assert(!g.state.flags.has('tv'));assert(!g.state.flags.has('map'));assert(!g.state.flags.has('terminal'));walk(g,2440);assert(g.state.flags.has('rich'));walk(g,2900);assert(g.state.flags.has('ape'));walk(g,3510);g.interact();assert.equal(g.dialogue.encounter?.id,'board');const before=g.state.netWorth;g.advance('BUY TICKET · $12');assert.equal(g.state.netWorth,before-12);assert(g.state.flags.has('ticket'));completeDialogue(g);g.interact();assert.equal(g.dialogue.nodeId,'owned');completeDialogue(g);assert.equal(g.state.netWorth,before-12,'ticket charged only once');walk(g,7100);assert.equal(g.state.phase,'ending');assert(g.state.flags.has('complete'));assert(g.challengeTime>=15&&g.challengeTime<25,'construction run pacing');
for(const idea of ['seven','Twelve','first mission','New chapters','monkes','token of the RichMonke universe','community','top'])assert(transcript.some(s=>s.toLowerCase().includes(idea.toLowerCase())),idea+' must be on main path');
assert(transcript.length<=15,'main story stays short');
const fare=new GameRuntime();fare.state.flags.add('ape');open(fare,'board');fare.advance('BUY TICKET · $12');assert.equal(fare.dialogue.nodeId,'short');assert.equal(fare.state.netWorth,7);assert(!fare.state.flags.has('ticket'));completeDialogue(fare);
const freeRoad=new GameRuntime();for(const f of ['doubter','stop','left-stop','rich','ape'])freeRoad.state.flags.add(f);freeRoad.setPhase('playing');freeRoad.player.x=4430;step(freeRoad,1,1);assert(freeRoad.player.x>4500,'no checkpoint wall');assert(!freeRoad.mission.shouldEnd(7090,freeRoad.state.flags),'ticket and story needed for episode finale');
const mainBoxes=transcript.length;for(const id of ['tv','map','terminal','poster','vending','graffiti']){open(g,id);if(id==='map'||id==='terminal')g.closeDialogue();else completeDialogue(g);}assert.equal(g.state.secrets.size,3);await g.vote('Harbor');await assert.rejects(()=>new LocalVoteAdapter().save('Moon'));
for(const item of pickups.filter(i=>i.kind==='banana'))g.state.collected.add(item.id);const achievement=new AchievementSystem();assert(achievement.check(g.state));assert(!achievement.check(g.state));g.state.scene='street';g.save();const restored=new GameState(),rp=new Player();assert(new ProgressStore().load(restored,rp));assert.equal(restored.netWorth,g.state.netWorth,'spent fare persists');assert(restored.flags.has('ticket'));assert.equal(restored.vote,'Harbor');assert.equal(new CollectibleSystem().count(restored),5);
memory.set(new ProgressStore().key,'{bad');assert.equal(new ProgressStore().load(new GameState(),new Player()),false);
memory.set(new ProgressStore().key,JSON.stringify({version:2,x:999999,collected:['fake','cash-0','cash-0'],flags:['fake'],vote:'Moon'}));const sanitized=new GameState(),sp=new Player();assert(new ProgressStore().load(sanitized,sp));assert.equal(sanitized.netWorth,8);assert.equal(sp.x,7090);assert.equal(sanitized.vote,null);assert.equal(sanitized.flags.size,0);

const otherChoice=new GameRuntime();open(otherChoice,'doubter');otherChoice.advance('GOT A BETTER IDEA?');assert.equal(otherChoice.dialogue.node?.speaker,'hero');completeDialogue(otherChoice);assert(otherChoice.state.flags.has('doubter'));
const inside=new GameState(),insidePlayer=new Player();inside.scene='stop';inside.flags.add('stop');inside.flags.add('doubter');insidePlayer.x=420;new ProgressStore().save(inside,insidePlayer,1405);const resumed=new GameRuntime();resumed.init();assert.equal(resumed.state.scene,'street');assert(resumed.state.flags.has('left-stop'),'interior resume cannot strand the next story event');
const camera=new Camera();camera.update(dt,new Player(),1280,false);assert(camera.x>=0);
console.log('PASS: complete physical episode walk, main story comprehension, optional shop displays, money purpose, one-time ticket purchase, no checkpoint barrier, 15–25 second run, movement/collision/jumps, optional secrets/vote, persistence and migration.');
console.log('Main-path dialogue boxes:',mainBoxes,'Construction seconds:',g.challengeTime.toFixed(1));


