import { build } from 'rolldown';
import { mkdir, cp, writeFile, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const basePath = (process.env.BASE_PATH || '').replace(/\/+$/, '');
const publicPath = (path) => `${basePath}${path}`;
await mkdir('dist', { recursive: true });
await build({ input: 'client.tsx', platform: 'browser', resolve: { alias: { '@': resolve('.') } }, transform: { jsx: { runtime: 'automatic' }, define: { 'process.env.NODE_ENV': JSON.stringify('production'), __RICHMONKE_BASE_PATH__: JSON.stringify(basePath) } }, output: { dir: 'dist', entryFileNames: 'game.js', assetFileNames: '[name][extname]', minify: true } });
const css = await readFile('game/game.css', 'utf8');
await writeFile('dist/game.css', css.replaceAll("url('/assets/", `url('${publicPath('/assets/')}`));
await cp('public', 'dist', { recursive: true });
const html = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#11182c"><meta name="description" content="Start with $7. Enter Monke City. A playable RICHMONKE story."><title>MONKE CITY — A RICHMONKE Story</title><link rel="icon" href="${publicPath('/favicon.svg')}"><link rel="stylesheet" href="${publicPath('/game.css')}"></head><body><div id="root"></div><script type="module" src="${publicPath('/game.js')}"></script></body></html>`;
await writeFile('dist/index.html', html);
await writeFile('dist/404.html', html);
await writeFile('dist/.nojekyll', '');
console.log('Built MONKE CITY static game in dist/');
